### ISSUE TITLE
Texture Editor fails

### ISSUE THREAD

**Issue by Roareye** [X-Hax/sa_tools#174]
Attempting to extract some PVM files (only 2) and just crashes every single time with the following error message.
Does the PVM file need to be in the same location as the program? I have no idea why it's going into the D:/ drive as it's stored on X:/ and the files are stored on E:/ - Is this oddity causing it to fail? If so, how do I fix it since I've not told it to go near D drive at all.

Thanks in advance.

------------------------------------------------------------------------------------------------
Program: Texture Editor
Build Date: 06/06/2021 18:02:27
OS Version: Microsoft Windows NT 6.2.9200.0
Log:
Texture Editor: New log entry on 18/06/2021 16:23:09
Build date:06/06/2021 18:02:27
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at System.IO.Path.GetFileNameWithoutExtension(String path)
   at TextureEditor.MainForm.GetTexturesFromFile(String fname) in D:\Programs\sa_tools\TextureEditor\MainForm.cs:line 313
   at TextureEditor.MainForm.LoadArchive(String filename) in D:\Programs\sa_tools\TextureEditor\MainForm.cs:line 402
   at TextureEditor.MainForm.openToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Programs\sa_tools\TextureEditor\MainForm.cs:line 515
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
That was fast. I'm guessing you're trying to extract the PVMs from Dream Passport 3. The crashing PVMs have some garbage bytes in their PVR entry names that the tool didn't account for. I fixed it but the fix is in a branch we haven't merged yet.

Here are the extracted textures that I got with the updated tool:
[DPDL.zip](https://github.com/X-Hax/sa_tools/files/6677972/DPDL.zip)
