### ISSUE TITLE
SAMDL Bad Image Format Exception

### ISSUE THREAD

**Issue by RaggedySLG3** [X-Hax/sa_tools#201]
Program: SAMDL
Build Date: 12/09/2021 03:39:21
OS Version: Microsoft Windows NT 10.0.19044.0
Log:
System.BadImageFormatException: Se ha intentado cargar un programa con un formato incorrecto. (0x8007000B)
   at SharpDX.Direct3D9.D3DX9.D3DXCreateSprite_(Void* arg0, Void* arg1)
   at SharpDX.Direct3D9.D3DX9.CreateSprite(Device deviceRef, Sprite spriteOut)
   at SharpDX.Direct3D9.Sprite..ctor(Device device)
   at SAModel.SAEditorCommon.OnScreenDisplay..ctor(Device device, RawColorBGRA color) in D:\Programs\sa_tools\Libraries\SAEditorCommon\Logging.cs:line 118
   at SAModel.SAMDL.MainForm.MainForm_Load(Object sender, EventArgs e) in D:\Programs\sa_tools\SAMDL\MainForm.cs:line 272
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at SAModel.SAMDL.MainForm.WndProc(Message& m) in D:\Programs\sa_tools\SAMDL\MainForm.cs:line 60
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
Do you have DirectX 9.0 installed? https://github.com/X-Hax/sa_tools/wiki/System-Requirements

**Comment by PiKeyAr** [comment]
Please reopen if still applicable
