### ISSUE TITLE
SAMDL Null Reference Exception

### ISSUE THREAD

**Issue by RaggedySLG3** [X-Hax/sa_tools#202]
Program: SAMDL
Build Date: 12/09/2021 03:39:21
OS Version: Microsoft Windows NT 10.0.19044.0
Log:
System.NullReferenceException: Object reference not set to an instance of an object.
   at SAModel.SAMDL.MainForm.buttonSolid_Click(Object sender, EventArgs e) in D:\Programs\sa_tools\SAMDL\MainForm.cs:line 2906
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
Do you have DirectX 9.0 installed? https://github.com/X-Hax/sa_tools/wiki/System-Requirements

**Comment by PiKeyAr** [comment]
Please reopen if still applicable
