### ISSUE TITLE
Argument Exception

### ISSUE THREAD

**Issue by RaggedySLG3** [X-Hax/sa_tools#203]
Program: SAMDL
Build Date: 12/11/2021 12:14:25
OS Version: Microsoft Windows NT 10.0.19044.0
Log:
System.ArgumentException: An item with the same key has already been added. Key: Sonic_Head_Sonic_Head.004
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.NJS_OBJECT.GetBytes(UInt32 imageBase, Boolean DX, Dictionary`2 labels, UInt32& address) in D:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 227
   at SAModel.ModelFile.SaveToFile(String filename) in D:\Programs\sa_tools\Libraries\SAModel\ModelFile.cs:line 300
   at SAModel.SAMDL.MainForm.Save(String fileName, Boolean saveAnims) in D:\Programs\sa_tools\SAMDL\MainForm.cs:line 971
   at SAModel.SAMDL.MainForm.saveMenuItem_Click(Object sender, EventArgs e) in D:\Programs\sa_tools\SAMDL\MainForm.cs:line 1004
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
Does your model have multiple nodes with identical labels?

**Comment by PiKeyAr** [comment]
Please reopen if still applicable
