### ISSUE TITLE
ive renamed the model mulpitple times i dont get it WHY CANT IT FIND THE MODEL

### ISSUE THREAD

**Issue by masontay1rr** [X-Hax/sa_tools#233]
Program: SAMDL
Build Date: 05/28/2022 15:09:08
OS Version: Microsoft Windows NT 10.0.19044.0
Log:
System.IO.FileNotFoundException: Could not find file 'C:\Users\\OneDrive\Desktop\models\NOOB\head\sonic'.
File name: 'C:\Users\\OneDrive\Desktop\models\NOOB\head\sonic'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at SAModel.Direct3D.Extensions.obj2nj(String objfile, String[] textures) in C:\Programs\sa_tools\Libraries\SAModel.Direct3D\ExtensionsLegacy.cs:line 48
   at SAModel.SAMDL.MainForm.ImportOBJLegacy(NJS_OBJECT obj, String filename) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 3568
   at SAModel.SAMDL.MainForm.selectedLegacyOBJImportToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 3598
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

- [ ] I am using the latest version of SA Tools.

- [ ] The problem is consistently reproducible.

- [ ] I have looked through the list of open issues and confirmed that the problem hasn't been reported before.

**Describe the bug/request**
A clear and concise description of what the issue is.

**To Reproduce (if applicable)**

**Expected behavior**

**Screenshots**

**Files**
If the program crashes during work with a specific file (such as a custom level), attach it to this report.

**Log**
If the program crashed with a bug report dialog, please paste the contents of the report here.

**Additional context**

**Comment by PiKeyAr** [comment]
Please read the template when creating a new issue.
