### ISSUE TITLE
SA Tools doesn't build

### ISSUE THREAD

**Issue by Maxx-Light** [X-Hax/sa_tools#245]
Program: SA Tools Hub
Build Date: 06/18/2023 22:41:03
OS Version: Microsoft Windows NT 10.0.19045.0
Log:
System.ArgumentException: An item with the same key has already been added. Key: Windy Valley Messages
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at SAModel.SAEditorCommon.ManualBuildWindow.IniExportButton_Click(Object sender, EventArgs e) in C:\Programs\sa_tools\SAToolsHub\Forms\ManualBuildWindow.cs:line 370
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
This was probably fixed some time ago.
