### ISSUE TITLE
SAMDL suddenly stopped importing or exporting

### ISSUE THREAD

**Issue by EnterPlayerOne** [X-Hax/sa_tools#247]
Hi. Very new to all of this, started modding a fortnight ago and have been having a grand time with no issues making accessories for chao. now whenever I try to import my custom .obj files from blender, or to export from samdl for use in blender, I get the following issue. Any advice greatly appreciated, I have no clue what I'm looking at.

Program: SAMDL
Build Date: 09/21/2023 05:27:22
OS Version: Microsoft Windows NT 6.3.9600.0
Log:
Loading the model from C:\Users\Tris\Desktop\wtf.dae failed for the following reason(s):
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Assimp.NodeCollection.get_Item(Int32 index)
   at SAModel.SAMDL.MainForm.ImportModel_Assimp(String objFileName, Boolean importAsSingle, Boolean selected, Boolean importColladaRoot) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 2361
   at SAModel.SAMDL.MainForm.ImportModelFromFile(String modelFilename) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 237
   at SAModel.SAMDL.MainForm.LoadFile(String filename, Boolean cmdLoad) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 625
   at SAModel.SAMDL.MainForm.openToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 417

**Comment by EnterPlayerOne** [comment]
Program: SAMDL
Build Date: 09/21/2023 05:27:22
OS Version: Microsoft Windows NT 6.3.9600.0
Log:
Loading the model from C:\Users\Tris\Desktop\silver hood.obj failed for the following reason(s):
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SAModel.SAEditorCommon.Import.AssimpStuff.AssimpImportChunk(List`1 materials, List`1 meshes, String[] textures) in C:\Programs\sa_tools\Libraries\SAEditorCommon\Import\AssimpStuff.cs:line 1262
   at SAModel.SAEditorCommon.Import.AssimpStuff.AssimpImportNonWeighted(Scene scene, Node node, ModelFormat format, String[] textures, Boolean asSingle) in C:\Programs\sa_tools\Libraries\SAEditorCommon\Import\AssimpStuff.cs:line 1084
   at SAModel.SAEditorCommon.Import.AssimpStuff.AssimpImport(Scene scene, Node node, ModelFormat modelFormat, String[] texInfo, Boolean asSingle) in C:\Programs\sa_tools\Libraries\SAEditorCommon\Import\AssimpStuff.cs:line 918
   at SAModel.SAMDL.MainForm.ImportModel_Assimp(String objFileName, Boolean importAsSingle, Boolean selected, Boolean importColladaRoot) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 2362
   at SAModel.SAMDL.MainForm.ImportModelFromFile(String modelFilename) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 237
   at SAModel.SAMDL.MainForm.LoadFile(String filename, Boolean cmdLoad) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 625
   at SAModel.SAMDL.MainForm.openToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 417

**Comment by MainMemory** [comment]
I'll look into it, but you do know there's [a Blender addon](https://x-hax.github.io/SonicAdventureBlenderIODocs/) that works way better than SA Tools ever will, right?
