### ISSUE TITLE
SAIO can't import

### ISSUE THREAD

**Issue by EnterPlayerOne** [X-Hax/sa_tools#248]
Hi, Can't find any other information so have had to post here.

Trying to use the SAIO add-on. Blender is up to date. Consistently and any time I try to import or export sa2mdl it coughs up some errors. any insight greatly appreciated. Log as follows:

Python: Traceback (most recent call last):
  File "C:\Users\Tris\AppData\Roaming\Python\Python310\site-packages\pythonnet\__init__.py", line 77, in _create_runtime_from_spec
    return clr_loader.get_coreclr(**params)
  File "C:\Users\Tris\AppData\Roaming\Python\Python310\site-packages\clr_loader\__init__.py", line 142, in get_coreclr
    impl = DotnetCoreRuntime(runtime_config=runtime_config, dotnet_root=dotnet_root)
  File "C:\Users\Tris\AppData\Roaming\Python\Python310\site-packages\clr_loader\hostfxr.py", line 23, in __init__
    self._handle = _get_handle(self._dll, self._dotnet_root, runtime_config)
  File "C:\Users\Tris\AppData\Roaming\Python\Python310\site-packages\clr_loader\hostfxr.py", line 138, in _get_handle
    check_result(res)
  File "C:\Users\Tris\AppData\Roaming\Python\Python310\site-packages\clr_loader\util\__init__.py", line 42, in check_result
    raise error
clr_loader.util.clr_error.ClrError: 0x80008093: InvalidConfigFile

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tris\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SonicAdventureBlenderIO-main\source\register\operators\base.py", line 26, in execute
    return self._execute(context)
  File "C:\Users\Tris\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SonicAdventureBlenderIO-main\source\register\operators\import_operators.py", line 77, in _execute
    dll_utils.load_library()
  File "C:\Users\Tris\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SonicAdventureBlenderIO-main\source\utility\dll_utils.py", line 29, in load_library
    pythonnet.load("coreclr", runtime_config=runtime_config)
  File "C:\Users\Tris\AppData\Roaming\Python\Python310\site-packages\pythonnet\__init__.py", line 135, in load
    set_runtime(runtime, **params)
  File "C:\Users\Tris\AppData\Roaming\Python\Python310\site-packages\pythonnet\__init__.py", line 29, in set_runtime
    runtime = _create_runtime_from_spec(runtime, params)
  File "C:\Users\Tris\AppData\Roaming\Python\Python310\site-packages\pythonnet\__init__.py", line 90, in _create_runtime_from_spec
    raise RuntimeError(
RuntimeError: Failed to create a .NET runtime (coreclr) using the
                parameters {'runtime_config': 'C:\\Users\\Tris\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\SonicAdventureBlenderIO-main\\DLL\\SA3D.Modeling.Blender.runtimeconfig.json'}.

**Comment by MainMemory** [comment]
https://github.com/X-Hax/SonicAdventureBlenderIO/issues
