### ISSUE TITLE
Unable to export files with SA Tools

### ISSUE THREAD

**Issue by ConnoisseurDexterity** [X-Hax/sa_tools#259]
Lastest version of SA Tools -> 6th April 2024 09:26:16

Unable to export files. Attempted to export LandTable, objects and texlists for Green Hill. Happens with any stage.

Program: SA Tools Hub
Build Date: 04/06/2024 09:26:16
OS Version: Microsoft Windows NT 10.0.19045.0
Log:
System.Collections.Generic.KeyNotFoundException: The given key 'Basic Test LandTable' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SAModel.SAEditorCommon.DLLModGenerator.DLLModGen.<>c__DisplayClass6_0.<ExportINIManual>b__1(KeyValuePair`2 i) in C:\Programs\sa_tools\Libraries\SAEditorCommon\ModBuilding\DLLModGen.cs:line 397
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at SAModel.SAEditorCommon.DLLModGenerator.DLLModGen.ExportINIManual(DllIniData IniData, Dictionary`2 itemsToExport, String fileName) in C:\Programs\sa_tools\Libraries\SAEditorCommon\ModBuilding\DLLModGen.cs:line 396
   at SAModel.SAEditorCommon.ManualBuildWindow.IniExportButton_Click(Object sender, EventArgs e) in C:\Programs\sa_tools\SAToolsHub\Forms\ManualBuildWindow.cs:line 369
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
According to my tests, this has been fixed in the latest version.
