### ISSUE TITLE
Can't create new project from Korean SADX

### ISSUE THREAD

**Issue by hankju84** [X-Hax/sa_tools#260]
**Describe the bug/request**
When I try to create new project from Korean SADX, SA Tools just crash

**To Reproduce (if applicable)**
1. Create New Project
2. Select a Template as 'PC - Korean version of SADX'
3. Select game path, then crash

**Log**
Program: SA Tools Hub
Build Date: 04/18/2024 05:49:03
OS Version: Microsoft Windows NT 10.0.26100.0
Log:
System.NullReferenceException: Object reference not set to an instance of an object.
   at SAModel.SAEditorCommon.ProjectManagement.ProjectFunctions.checkFileHashes(String gameHashes, String checkFileHash) in C:\Programs\sa_tools\Libraries\SAEditorCommon\ProjectManagement\ProjectManagement.cs:line 335
   at SAModel.SAEditorCommon.ProjectManagement.ProjectFunctions.openTemplateFile(String templateFilePath, Boolean ignoreGamePath) in C:\Programs\sa_tools\Libraries\SAEditorCommon\ProjectManagement\ProjectManagement.cs:line 422
   at SAToolsHub.newProj.openTemplate(String templateSplit) in C:\Programs\sa_tools\SAToolsHub\Forms\newProj.cs:line 291
   at SAToolsHub.newProj.comboBox1_SelectedIndexChanged(Object sender, EventArgs e) in C:\Programs\sa_tools\SAToolsHub\Forms\newProj.cs:line 185
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
Works fine for me. Are you sure your `sonic.exe` hasn't been tampered with? The MD5 of SonoKong's sonic.exe is `6b3c7a0013cbfd9b12c3765e9ba3a73e`.

**Comment by PiKeyAr** [comment]
Oh, nevermind, I misread. This should be fixed in the latest version.

**Comment by hankju84** [comment]
It works. Thank you!
