### ISSUE TITLE
When i open the SAMDL,it's crash with the following error:DIINotFoundException.What can i do now ??

### ISSUE THREAD

**Issue by jnwai** [X-Hax/sa_tools#264]
Program: SAMDL
Build Date: 06/26/2024 18:10:24
OS Version: Microsoft Windows NT 10.0.16299.0
Log:
System.DllNotFoundException: Unable to load DLL 'd3dx9_43.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at SharpDX.Direct3D9.D3DX9.D3DXCreateSprite_(Void* arg0, Void* arg1)
   at SharpDX.Direct3D9.D3DX9.CreateSprite(Device deviceRef, Sprite spriteOut)
   at SharpDX.Direct3D9.Sprite..ctor(Device device)
   at SAModel.SAEditorCommon.OnScreenDisplay..ctor(Device device, RawColorBGRA color) in C:\Programs\sa_tools\Libraries\SAEditorCommon\Logging.cs:line 130
   at SAModel.SAMDL.MainForm.MainForm_Load(Object sender, EventArgs e) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 285
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
You need to install DirectX 9.0c, see https://github.com/X-Hax/sa_tools/wiki/System-Requirements
