### ISSUE TITLE
So i open SAMDL (again) and this happen, how can i fix that ??

### ISSUE THREAD

**Issue by jnwai** [X-Hax/sa_tools#265]
Program: SAMDL
Build Date: 06/29/2024 10:05:41
OS Version: Microsoft Windows NT 10.0.16299.0
Log:
Loading the model from C:\Users\Administrator\Desktop\Sâm\CTBH HCM 2020\sonic\sadx\SADX\SONICADVENTUREDX\SONICADVENTUREDX\mods\DX Characters Refined\SADXR.dll failed for the following reason(s):
System.ArgumentOutOfRangeException: Number was less than the array's lower bound in the first dimension. (Parameter 'sourceIndex')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at SAModel.ByteConverter.ToInt32(Byte[] value, Int32 startIndex) in C:\Programs\sa_tools\Libraries\SAModel\ByteConverter.cs:line 97
   at SAModel.BasicAttach..ctor(Byte[] file, Int32 address, UInt32 imageBase, Boolean DX, Dictionary`2 labels) in C:\Programs\sa_tools\Libraries\SAModel\BasicAttach.cs:line 41
   at SAModel.Attach.Load(Byte[] file, Int32 address, UInt32 imageBase, ModelFormat format, Dictionary`2 labels) in C:\Programs\sa_tools\Libraries\SAModel\Attach.cs:line 76
   at SAModel.NJS_OBJECT..ctor(Byte[] file, Int32 address, UInt32 imageBase, ModelFormat format, NJS_OBJECT parent, Dictionary`2 labels, Dictionary`2 attaches) in C:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 136
   at SAModel.NJS_OBJECT..ctor(Byte[] file, Int32 address, UInt32 imageBase, ModelFormat format, Dictionary`2 labels, Dictionary`2 attaches) in C:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 103
   at SAModel.NJS_OBJECT..ctor(Byte[] file, Int32 address, UInt32 imageBase, ModelFormat format, Dictionary`2 attaches) in C:\Programs\sa_tools\Libraries\SAModel\NJS_OBJECT.cs:line 99
   at SAModel.SAMDL.MainForm.LoadBinFile(Byte[] file) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 810
   at SAModel.SAMDL.MainForm.LoadFile(String filename, Boolean cmdLoad) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 708
   at SAModel.SAMDL.MainForm.openToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 421

**Comment by PiKeyAr** [comment]
SAMDL isn't meant to open compiled mod DLL files.
