### ISSUE TITLE
TextureNotInitalized Exception error when saving Sonic textures

### ISSUE THREAD

**Issue by VannyBuns** [X-Hax/sa_tools#267]
Before creating a new issue, please read the following:

This issue tracker is for bug reports and feature requests. This is not the place to ask how to use the tools or where to find models etc. If you need help using the tools, check out the wiki or ask on Discord.

In addition, please confirm the following:

- [ x] I am using the latest version of SA Tools.

- [x ] The problem is consistently reproducible.

- [x ] I have looked through the list of open issues and confirmed that the problem hasn't been reported before.

**Describe the bug/request**
I cannot export the sonictex.prs back to a PRS file for the gamecube version. I get TextureFileNotInitalized. Every other export option works except for the GVM option.

**To Reproduce (if applicable)**
1.Open .prs files
2.Replace with modded files from .pak.
3.Export to GVM(renamed to prs).
**Expected behavior**
Saved successfully.
**Screenshots**
![Screenshot 2024-07-19 192955](https://github.com/user-attachments/assets/a6f9ddd0-3586-42d2-a15a-404e3b3888dd)

**Files**
sonictex.prs

**Log**
Program: Texture Editor
Build Date: 07/15/2024 10:59:56
OS Version: Microsoft Windows NT 10.0.19045.0
Log:
Texture Editor: New log entry on 7/19/2024 7:24:06 PM
Build date:07/15/2024 10:59:56
VrSharp.TextureNotInitalizedException: Cannot access this property as the texture is not initalized.
   at VrSharp.VrTextureEncoder.set_GlobalIndex(UInt32 value) in C:\Programs\sa_tools\Libraries\VrSharp\Core\VrTextureEncoder.cs:line 71
   at TextureEditor.MainForm.EncodeGVR(GvrTextureInfo tex) in C:\Programs\sa_tools\TextureEditor\MainForm.cs:line 1726
   at TextureEditor.MainForm.SaveTextures() in C:\Programs\sa_tools\TextureEditor\MainForm.cs:line 738
   at TextureEditor.MainForm.SaveAs(TextureFormat savefmt) in C:\Programs\sa_tools\TextureEditor\MainForm.cs:line 911
   at TextureEditor.MainForm.saveAsGVMToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Programs\sa_tools\TextureEditor\MainForm.cs:line 2281
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Additional context**
Didn't test the other mods I had besides the fileSelect_e which saved fine. Every .pak I have has a GVM header, so I want it to be accurate when I repack the iso.

**Comment by PiKeyAr** [comment]
Some time ago I was able to reproduce this, but when I finally got around to investigating it, I couldn't get it to happen with the current version anymore. Do you still have the files triggering this issue?
