### ISSUE TITLE
SAMDL has crashed with the following error:ArgumentOutOfRangeException 

### ISSUE THREAD

**Issue by jnwai** [X-Hax/sa_tools#269]
Program: SAMDL
Build Date: 06/29/2024 10:05:41
OS Version: Microsoft Windows NT 10.0.16299.0
Log:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')
   at System.BitConverter.ToInt16(Byte[] value, Int32 startIndex)
   at System.BitConverter.ToUInt16(Byte[] value, Int32 startIndex)
   at VrSharp.Pvr.PvrPixelCodec.Rgb565.DecodePixel(Byte[] source, Int32 sourceIndex, Byte[] destination, Int32 destinationIndex) in C:\Programs\sa_tools\Libraries\VrSharp\Pvr\PvrPixelCodec.cs:line 75
   at VrSharp.VrPixelCodec.DecodePalette(Byte[] source, Int32 sourceIndex, Int32 numEntries) in C:\Programs\sa_tools\Libraries\VrSharp\Core\VrCodec.cs:line 29
   at VrSharp.VrDataCodec.SetPalette(Byte[] palette, Int32 offset, Int32 numEntries) in C:\Programs\sa_tools\Libraries\VrSharp\Core\VrCodec.cs:line 87
   at VrSharp.VrTexture.SetPalette(VpPalette palette, Int32 bank) in C:\Programs\sa_tools\Libraries\VrSharp\Core\VrTexture.cs:line 475
   at VrSharp.Pvr.PvrTexture.SetPalette(PvpPalette clut, Int32 bank) in C:\Programs\sa_tools\Libraries\VrSharp\Pvr\PvrTexture.cs:line 270
   at ArchiveLib.PVMEntry.GetBitmap() in C:\Programs\sa_tools\Libraries\ArchiveLib\Puyo.cs:line 440
   at SAModel.Direct3D.TextureSystem.TextureArchive.GetTextures(String filename, Boolean& hasNames, String paletteFile) in C:\Programs\sa_tools\Libraries\SAModel.Direct3D\TextureSystem\TextureArchive.cs:line 95
   at SAModel.SAMDL.MainForm.AddTextures(String[] filenames, String paletteFile) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 3949
   at SAModel.SAMDL.MainForm.LoadModelInfo(ModelLoadInfo info) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 4251
   at SAModel.SAMDL.MainForm.LoadProject(String filename) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 4320
   at SAModel.SAMDL.MainForm.LoadFile(String filename, Boolean cmdLoad) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 671
   at SAModel.SAMDL.MainForm.LoadFileList(String[] files, Boolean cmdLoad) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 199
   at SAModel.SAMDL.MainForm.MainForm_Load(Object sender, EventArgs e) in C:\Programs\sa_tools\SAMDL\MainForm.cs:line 364
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by PiKeyAr** [comment]
Looks like an incorrectly formatted PVR texture. Could you share the files that caused this error?

**Comment by jnwai** [comment]
Oh nevermind,i already fix it.
