### ISSUE TITLE
SA2PC project creation key 0 error

### ISSUE THREAD

**Issue by rin-ikagari** [X-Hax/sa_tools#278]
Before creating a new issue, please read the following:

This issue tracker is for bug reports and feature requests. This is not the place to ask how to use the tools or where to find models etc. If you need help using the tools, check out the wiki or ask on Discord.

In addition, please confirm the following:

- [X] I am using the latest version of SA Tools.

- [X] The problem is consistently reproducible.

- [ ] I have looked through the list of open issues and confirmed that the problem hasn't been reported before.

**Describe the bug/request**
A clear and concise description of what the issue is.

**To Reproduce (if applicable)**
Create new project, set it to SA2PC template

**Expected behavior**
the project opens

**Screenshots**
![imagen](https://github.com/user-attachments/assets/a913fd80-36fd-40ff-ac1e-90fe3ad5e16b)

**Files**
If the program crashes during work with a specific file (such as a custom level), attach it to this report.

**Log**
Program: SA Tools Hub
Build Date: 11/13/2024 08:26:11
OS Version: Microsoft Windows NT 10.0.19042.0
Log:
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'notepad' with working directory 'E:\SteamLibrary\steamapps\common\Sonic Adventure 2'. El sistema no puede encontrar el archivo especificado.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at SAToolsHub.newProj.BackgroundWorker1_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in C:\Programs\sa_tools\SAToolsHub\Forms\newProj.cs:line 636
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

**Additional context**

**Comment by PiKeyAr** [comment]
Split error log:
```
Program: SA Tools Hub
Build Date: 11/21/2024 21:28:24
OS Version: Microsoft Windows NT 10.0.26100.0
Log:
System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SplitTools.SAArc.sa2MDL.Split(String filePath, String outputFolder, String[] animationPaths, String mdllabelfile, String mtnlabelfile, String exmtnfile) in D:\GitHub\sa_tools\Libraries\SplitTools\SplitMDL.cs:line 134
   at SAModel.SAEditorCommon.ProjectManagement.ProjectFunctions.SplitTemplateMDLEntry(SplitEntryMDL splitMDL, ProgressDialog progress, String gameFolder, String outputFolder, String iniFolder, Boolean overwrite) in D:\GitHub\sa_tools\Libraries\SAEditorCommon\ProjectManagement\ProjectManagement.cs:line 704
   at SAToolsHub.newProj.splitGame(String game, ProgressDialog progress, DoWorkEventArgs e) in D:\GitHub\sa_tools\SAToolsHub\Forms\newProj.cs:line 535
   at SAToolsHub.newProj.backgroundWorker1_DoWork(Object sender, DoWorkEventArgs e) in D:\GitHub\sa_tools\SAToolsHub\Forms\newProj.cs:line 620
   at SAToolsHub.newProj.btnCreate_Click(Object sender, EventArgs e) in D:\GitHub\sa_tools\SAToolsHub\Forms\newProj.cs:line 164
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

**Comment by BeezareCalm** [comment]
for some reason this only happened to me when i downloaded it from the Sonic Adventure Blender I/O website. make sure you download it from the github, or https://github.com/X-Hax/sa_tools/blob/master/README.md .
